"""migrate second

Revision ID: 5ffa93784bbc
Revises: 
Create Date: 2024-02-06 10:09:58.222477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffa93784bbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookTable',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('binding', sa.String(), nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('isbn'),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('publisher_date', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookTable')
    # ### end Alembic commands ###
