"""models n config

Revision ID: d797134b7e85
Revises: 
Create Date: 2024-02-06 13:39:30.219675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd797134b7e85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('publisher_date', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=False))
        batch_op.alter_column('index',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('binding',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('publisher',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('dimension',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_index('ix_bookTable_index')
        batch_op.drop_column('publish date')
        batch_op.drop_column('ISBN')
        batch_op.drop_column('page count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookTable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ISBN', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('publish date', sa.TEXT(), nullable=True))
        batch_op.create_index('ix_bookTable_index', ['index'], unique=False)
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('dimension',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('publisher',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('binding',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('index',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('page_count')
        batch_op.drop_column('publisher_date')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
